### ISSUE TITLE
A page reloads redirects docs to URI without /docs in the URL

### ISSUE THREAD

**Issue by muse-sisay** [konstructio/kubefirst-docs#771]
### What type of suggestions?

Something's not working

### What page is concerned?

https://kubefirst.konstruct.io/docs/do/overview

### What version of the docs?

2.6

### What is the issue?

A page reload, for example, in `https://kubefirst.konstruct.io/docs/do/overview` redirects to `https://kubefirst.konstruct.io/do/overview/`. The redirect removes `/docs` from the URL. I believe this is because of nginx rewrite target which replaces rewrites the URI with out docs.

```
  nginx.ingress.kubernetes.io/rewrite-target: /$1
hosts:
  - host: kubefirst-docs-production.mgmt-24.konstruct.io
    paths:
      - path: /
        pathType: Prefix
  - host: kubefirst.konstruct.io
    paths:
      - path: /docs/?(.*)
        pathType: ImplementationSpecific
```

Additionall, the following redirects don't work as they previously did
- `https://kubefirst.konstruct.io/docs/digitalocean/overview/` -> `https://kubefirst.konstruct.io/docs/do/overview/`
- `https://kubefirst.konstruct.io/docs/google/overview/` -> `https://kubefirst.konstruct.io/docs/gcp/overview/`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
